### ISSUE TITLE
old docker-compose format doesn't allow health checks

### ISSUE THREAD

**Issue by chadmiller** [InAnimaTe/docker-quake3#2]
Maybe something like this?

```
version: "3.3"
services:
    quake3:
        image: inanimate/quake3
        restart: always
        hostname: docker-q3
        ports:
           - "27960:27960/udp"
        volumes:
           - baseq3/:/usr/share/games/quake3/baseq3/
           - server.cfg:/usr/share/games/quake3/baseq3/server.cfg
        healthcheck:
           test: ["CMD", "ps", "-C", "ioq3ded"]
```
